export const NAMES = [
  "Charles",
  "Al-Fayed",
  "Diana",
  "Myran",
  "Trafikfaran",
  "Larven",
  "Rännan",
  "Top Secret",
  "No Nonsense",
  "Tuna",
  "Fromage",
  "Le Look",
  "Thunderstorm",
  "Spettan",
  "Leibnitz",
  "Sunset Lorentzon",
  "NN",
  "Una Playa",
  "Dinosaur",
  "Kastaniel",
  "Regn-Estelle",
  "1/2 man, 1/2 Noodle",
  "Vanligt Fôlk",
  "Tarkan",
  "Mao",
  "Malou",
  "Scooby Snacks",
  "The Dark Lord",
  "The Brick",
];
